language: ruby
sudo: false
cache: bundler

script:
  - ./scripts/cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
