language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3

before_install:
  - npm --prefix="./public" install

script:
  - "./scripts/cibuild.sh"

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

deploy:
  provider: firebase
  skip_cleanup: true
  on:
    tags: false
    branch: master
