language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3

script:
  - "./scripts/cibuild.sh"

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

deploy:
  provider: firebase
  skip_cleanup: true
  on:
    tags: false
    branch: master
  token:
    secure: xfJLMnRmSEDM82mPB9iLhlV98l4Hj3DaeRLUYscSltgyYHRfu8TQULegBWeOJOQ/eEtdqyaUj9F088n2ecHhXnNUIbP5hh8iaZ5L3xX6Qz9fH/uhRqHVi0G4xzFWyrj+DDOEg+UYag25M19+G/9YTR0SMhLdtu/YGp0OQOELEMswUVj1yq3uRXGefayr3Kb0kuzPNV1SObjSrSllGoPpBH0nfRpHMtKZ8PwcfPH6RYazfYa1CQYdh4xhHtTSOEfOTfBYe77RgupK1hxhDXTcP+D55Uf788FQRtf/kdsa8VcxLDYzja9z5WrTtHbuiCkQvq2Al/Cm/FRqMB3lRHkPhclLDOffJhodGY7VidxoBGKaXR4D9DK5vZq3h+8w4vaG0MWziB9yP/szdqdUxZb6WS1mEqrl19Sjo9vSTftGBSi0L4OSIX1z1GCLSvO/pIdtqUVm5RFqaIE17H/USmGsx7kIgOMczWi+xNUFE/oE7pdkfJ6CcfM281FR050z4Zs1+4dsA0Q1dXRnV7TuGhPtgq4ntkDjd9Iqv+QF8ZaaRH+9lGYYbZvq6C4VzfKoUaZfIfusoiZVoyBkutuRsi5+aTFnoD4h3MBMojnU5HK/izOate9dSJdMtQpyoWlkMkJhWIGWo7HL4d3O75/6331zulxJ7Oy9lRDY9Cf2G0SY7cM=
