name: Spersonalizowane porady ze Szpitala w Ameryce
title: "Spersonalizowane porady ze Szpitala w Ameryce"
email: szpital@ameryka.com.pl
description: Aplikacja umoliwiająca przegladanie spersonalizowanych porad dla pacjentów od specjalistów Wojewódzkiego Szpitala Rehabilitacyjnego dla Dzieci w Ameryce.
url: ""
baseurl: "/"

# Build settings
markdown: kramdown
include: ["_pages"]

## Front matter defaults
defaults:

exclude:
    - vendor
    - Gemfile
    - Gemfile.lock

sass:
    sass_dir: _sass
    style: compressed
# Prayer:
#  Gloria Patri, et Filio, et Spiritui Sancto, sicut erat in principio et nunc et semper et in saecula
#  saeculorum. Amen. In te, Domine, speravi: non confundar in aeternum.
