name: Spersonalizowane porady ze Szpitala w Ameryce
title: "Spersonalizowane porady ze Szpitala w Ameryce"
email: szpital@ameryka.com.pl
description: Aplikacja umoliwiająca przegladanie spersonalizowanych porad dla pacjentów od specjalistów Wojewódzkiego Szpitala Rehabilitacyjnego dla Dzieci w Ameryce.
url: ""
baseurl: "/"

# Build settings
markdown: kramdown
include: ["_pages"]

## Front matter defaults
defaults:

gems:
  - jekyll-seo-tag

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  load_paths:
    - _sass
    - node_modules

text:
  navbar:
    title: "Szpital Ameryka"
  header:
    suptitle: "Wojewódzki Szpital Rehabilitacyjny dla Dzieci w Ameryce"
    title: "Porady medyczne od naszych specjalistów"

links:
  author: https://jedrzej.lewandowski.doctor/
  operator: https://www.ameryka.com.pl/
  privacyPolicy: https://www.ameryka.com.pl/pl/dla-pacjenta/ochrona-danych-osobowych
  license: https://www.gnu.org/licenses/gpl-3.0.html
  advicePanel: /advice-panel
  advicePanelOnline: /advice-panel
  advicePanelDownload: /advice-app-download
  roleManagement: /role-management/
  authorEmailSplit: jedrzej [at] lewandowski.doctor
  publicIssueEmail: szpital@ameryka.com.pl
# Prayer:
#  Gloria Patri, et Filio, et Spiritui Sancto, sicut erat in principio et nunc et semper et in saecula
#  saeculorum. Amen. In te, Domine, speravi: non confundar in aeternum.
